"""Base repository protocols."""

from __future__ import annotations

from typing import Any, Protocol, TypeVar

T = TypeVar("T")


class Repository(Protocol[T]):
    """Generic async repository interface."""

    async def get(self, id: str) -> T | None: ...
    async def list(self, skip: int = 0, limit: int = 100, **filters: Any) -> list[T]: ...
    async def create(self, entity: T) -> T: ...
    async def update(self, entity: T) -> T: ...
    async def delete(self, id: str) -> bool: ...
    async def count(self, **filters: Any) -> int: ...
