"""Campaign repository protocol."""

from __future__ import annotations

from typing import Protocol

from eskimos.core.entities.campaign import Campaign, CampaignStatus


class CampaignRepository(Protocol):
    """Repository for Campaign entities."""

    async def get(self, id: str) -> Campaign | None: ...
    async def list(self, skip: int = 0, limit: int = 100,
                   status: CampaignStatus | None = None) -> list[Campaign]: ...
    async def create(self, campaign: Campaign) -> Campaign: ...
    async def update(self, campaign: Campaign) -> Campaign: ...
    async def delete(self, id: str) -> bool: ...
    async def count(self, status: CampaignStatus | None = None) -> int: ...
    async def get_by_status(self, status: CampaignStatus) -> list[Campaign]: ...
