"""Contact repository protocol."""

from __future__ import annotations

from typing import Protocol

from eskimos.core.entities.contact import Blacklist, Contact, ContactStatus


class ContactRepository(Protocol):
    """Repository for Contact entities."""

    async def get(self, id: str) -> Contact | None: ...
    async def list(self, skip: int = 0, limit: int = 100,
                   campaign_id: str | None = None,
                   status: ContactStatus | None = None) -> list[Contact]: ...
    async def create(self, contact: Contact) -> Contact: ...
    async def update(self, contact: Contact) -> Contact: ...
    async def delete(self, id: str) -> bool: ...
    async def count(self, campaign_id: str | None = None,
                    status: ContactStatus | None = None) -> int: ...
    async def get_by_phone(self, phone: str) -> Contact | None: ...
    async def get_active_for_campaign(self, campaign_id: str) -> list[Contact]: ...
    async def bulk_create(self, contacts: list[Contact]) -> int: ...


class BlacklistRepository(Protocol):
    """Repository for Blacklist entries."""

    async def get(self, id: str) -> Blacklist | None: ...
    async def get_by_phone(self, phone: str) -> Blacklist | None: ...
    async def create(self, entry: Blacklist) -> Blacklist: ...
    async def delete(self, id: str) -> bool: ...
    async def is_blacklisted(self, phone: str) -> bool: ...
    async def list_all(self) -> list[Blacklist]: ...
